
export const WILAYAS_DATA: Record<string, string[]> = {
  "01 - Adrar": ["Adrar", "Tamest", "Charouine", "Reggane", "In Zghmir", "Tit", "Tsabit", "Timokten", "Bouda", "Aoulef", "Akabli", "Fenoughil", "Sali", "Sebaa", "Ouled Ahmed Timmi", "Tamantit", "Aougrout", "Deldoul"],
  "02 - Chlef": ["Chlef", "Ténès", "Boukadir", "Oued Fodda", "Ouled Fares", "Chettia", "Moussadek", "Harchoun", "Sendjas", "Sidi Abderrahmane", "Sobha", "Oued Sly", "El Karimia", "El Hadjadj", "Benairia", "Labiod Medjadja", "Sidi Akkacha", "Bouzghaia", "Aïn Merane", "Breira", "Oulad Ben Abdelkader", "Talassa", "Herenfa", "Oued Goussine", "Dahra", "Benaiche", "Tadjena", "Boucigane"],
  "03 - Laghouat": ["Laghouat", "Ksar el Hirane", "Bennasser Benchohra", "Sidi Makhlouf", "Hassi Delaa", "Hassi R'Mel", "Aïn Madhi", "Tadjmout", "Kheneg", "Gueltat Sidi Saad", "Aïn Sidi Ali", "Beidha", "Brida", "El Ghicha", "Hadj Mechri", "Sebgag", "Taouiala", "Tadjrouna", "Aflou", "El Oukhir", "Oued Morra", "Oued M'zi", "El Haouaita", "Sidi Bouzid"],
  "04 - Oum El Bouaghi": ["Oum El Bouaghi", "Aïn Beïda", "Aïn M'lila", "Behir Chergui", "El Amiria", "Sigus", "El Belala", "Aïn Babouche", "Berriche", "Ouled Hamla", "Dhala", "Aïn Kercha", "Hanchir Toumgani", "El Fedjoudj Boughrara", "Aïn Zitoun", "Fkirina", "Oued Nini", "Meskiana", "El Djazia", "Zorg", "Ouled Gacem", "Ouled Zouaï", "Souk Naamane"],
  "05 - Batna": ["Batna", "Ghassira", "Maafa", "Menaa", "Seriana", "Tighanimine", "Yabous", "Ahmadi", "Aïn Djasser", "Aïn Touta", "Arris", "Barika", "Boulhilat", "Boumagueur", "Boumia", "Djerma", "El Hassi", "El Madher", "Fesdis", "Foum Toub", "Ichmoul", "Inoughissen", "Kimmel", "Ksar Bellezma", "Larbaa", "Lazrou", "Lemsane", "M'douchel", "Merouana", "N'Gaous", "Oued Chaaba", "Oued El Ma", "Oued Taga", "Ouled Ammar", "Ouled Fadel", "Ouled Sellam", "Ouled Si Slimane", "Ouyoun El Assafir", "Rahbat", "Ras El Aioun", "Sefiane", "Seggana", "Tazoult", "Teniet El Abed", "Tigharghar", "Tilhaou", "Timgad", "Tkout", "Zanat El Beida"],
  "06 - Béjaïa": ["Béjaïa", "Amizour", "Ferraoun", "Taourirt Ighil", "Chellata", "Tamokra", "Timzrit", "Souk El Tenine", "Mcisna", "Thinabdher", "Tichi", "Semaoun", "Kendira", "Tifra", "Ighram", "Amalou", "Ighil Ali", "Fenaïa Ilmaten", "Toudja", "Darguina", "Sidi-Ayad", "Aokas", "Beni Djellil", "Adekar", "Akbou", "Seddouk", "Tazmalt", "Aït R'zine", "Chemini", "Souk Oufella", "Taskriout", "Tibane", "Tala Hamza", "Barbacha", "Beni Ksila", "Ouzellaguen", "Bouhamza", "Beni Maouche", "Sidi Aïch", "El Kseur", "Melbou", "Oued Ghir", "Boudjellil"],
  "07 - Biskra": ["Biskra", "Oumache", "Branis", "Cheddi", "El Ghrous", "El Hajeb", "El Outaya", "Filiache", "Khenguet Sidi Nadji", "Lichana", "Lioua", "M'Chouneche", "Mekhadma", "M'Lili", "Tolga", "Bouchagroune", "Ain Zaatout", "Sidi Okba", "Sidi Khaled", "Djemorah", "Tolga", "Zeribet El Oued"],
  "08 - Béchar": ["Béchar", "Errouina", "Taghit", "Igli", "Mazzer", "Kenadsa", "Beni Abbes", "Beni Ikhlef", "Mechraa Houari Boumedienne", "Lahmar", "Mougheul", "Meredja", "Ouled Khoudir", "Tabelbala", "Abadla", "Kasdir"],
  "09 - Blida": ["Blida", "Boufarik", "Bougara", "Beni Mered", "Ouled Yaïch", "Larbaa", "Meftah", "Chréa", "El Affroun", "Wadi Djer", "Mouzaia", "Hammame Melouane", "Bouinan", "Soumaa", "Chebli", "Oued Alleug", "Benkhelil", "Guerrouaou", "Beni Tamou"],
  "10 - Bouira": ["Bouira", "Lakhdaria", "Sour El Ghozlane", "Aïn Bessem", "Bechloul", "M'Chedallah", "Kadiria", "Aomar", "Ahnif", "Haizer", "Taghzout", "Roumiz", "Sidi Yahia", "Dechmia", "El Hakimia", "Djebahia", "Guerrouma", "Maala", "Bouderbala", "Zbarbar"],
  "11 - Tamanrasset": ["Tamanrasset", "Abalessa", "In Amguel", "Idles", "Tazrouk", "Tin Zaouatine", "In Salah", "In Ghar", "In Guezzam"],
  "12 - Tébessa": ["Tébessa", "Bir el-Ater", "Morsott", "Ouenza", "Al-Hammamet", "Bekkaria", "Boukhadra", "Cheria", "El Aouinet", "El Kouif", "El Meridj", "El Mezeraa", "El Ogla", "Ferkane", "Guorriguer", "Negrine", "Safsaf El Ouesra", "Stah Guentis", "Tlidjene"],
  "13 - Tlemcen": ["Tlemcen", "Beni Mester", "Aïn Tallout", "Remchi", "El Feuila", "Sabra", "Ghazaouet", "Souani", "Azaïls", "Maghnia", "Hammam Boughrara", "Bab El Assa", "Marsa Ben M'Hidi", "Sebdou", "Beni Snous", "Bensekrane", "Amieur", "Chetouane", "Mansourah"],
  "14 - Tiaret": ["Tiaret", "Medroussa", "Rosfa", "Meghila", "Sebt", "Sidi Hosni", "Frenda", "Aïn Kermes", "Ksar Chellala", "Rechaiga", "Sougueur", "Mahdia", "Hamadia", "Oued Lilli", "Mechraa Sfa", "Rahouia"],
  "15 - Tizi Ouzou": ["Tizi Ouzou", "Azazga", "Azeffoun", "Beni Yenni", "Boghni", "Bouzeguène", "Draâ Ben Khedda", "Draâ El Mizan", "Iferhounène", "Larbaâ Nath Irathen", "Maâtkas", "Makouda", "Mekla", "Ouadhia", "Ouacif", "Ouaguenoun", "Tigzirt", "Tizi Gheniff", "Yakouren"],
  "16 - Alger": ["Alger Centre", "Madania", "Belouizdad", "Bab El Oued", "Bologhine", "Casbah", "Oued Koriche", "Bir Mourad Raïs", "Birkhadem", "Hydra", "Sidi M'Hamed", "Ben Aknoun", "El Biar", "Bouzareah", "Beni Messous", "Dely Ibrahim", "Hammamet", "Raïs Hamidou", "Hussein Dey", "Kouba", "Mohammadia", "Bourouiba", "El Harrach", "El Magharia", "Oued Smar", "Bordj El Kiffan", "Bab Ezzouar", "Dar El Beïda", "El Marsa", "Bordj El Bahri", "Rouïba", "Reghaïa", "H'Raoua", "Birtouta", "Tesala El Merdja", "Ouled Chebel", "Sidi Moussa", "Larbaâ", "Zeralda", "Staoueli", "Aïn Benian", "Mahelma", "Rahmania", "Souidania", "Cheraga", "Ouled Fayet", "Draria", "Saoula", "Douera", "Baba Hassen", "Khraicia"],
  "17 - Djelfa": ["Djelfa", "Messaad", "Aïn Oussera", "Hassi Bahbah", "Had Sahary", "Benhar", "Ain El Ibel", "Charef", "Idrissia", "Dar Chioukh", "Sidi Ladjel", "Selmana", "Guernini", "Amourah"],
  "18 - Jijel": ["Jijel", "Taher", "El Milia", "El Aouana", "Chekfa", "Ghebala", "Settara", "El Ancer", "Sidi Abdelaziz", "Kaous", "Emir Abdelkader", "Oued Adjoul", "Chahna", "Texenna", "Boudriaa Ben Yadjis", "Boussif Ouled Askeur", "Ziama Mansouriah"],
  "19 - Sétif": ["Sétif", "El Eulma", "Aïn Arnat", "Aïn Abessa", "Aïn Azel", "Aïn Lahdjar", "Guenzet", "Bouandas", "Beni Aziz", "Beni Ourtilane", "Amoucha", "Babel", "Salah Bey", "Hammame Guergour", "Tizi N'Bechar"],
  "20 - Saïda": ["Saïda", "Aïn El Hadjar", "Youb", "Hounaet", "Sidi Amar", "Sidi Boubekeur", "El Hassasna", "Maamora", "Sidi Ahmed", "Moulay Larbi"],
  "21 - Skikda": ["Skikda", "Azzaba", "El Harrouch", "Collo", "Tamalous", "Aïn Kechra", "Sidi Mezghiche", "Ben Azzouz", "Zitouna", "Ramdane Djamel", "Ouled Attia", "Djendel Saadi Mohamed"],
  "22 - Sidi Bel Abbès": ["Sidi Bel Abbès", "Tessala", "Sfisef", "Sidi Ali Benyoub", "Sidi Ali Boussidi", "Sidi Dahou de Zair", "Ben Badis", "Lamtar", "Merine", "Ras El Ma", "Moulay Slissen", "Tenira", "Telagh"],
  "23 - Annaba": ["Annaba", "Berrahal", "El Hadjar", "El Bouni", "Sidi Amar", "Chetaïbi", "Seraïdi", "Tréat", "Oued El Aneb", "Ain Berda"],
  "24 - Guelma": ["Guelma", "Héliopolis", "Oued Zenati", "Bouchegouf", "Guelaat Bou Sbaa", "Nechmaya", "Bouati Mahmoud", "Medjez Amar", "Huari Boumediene", "Ain Sandel", "Bou Hamdane"],
  "25 - Constantine": ["Constantine", "El Khroub", "Hamma Bouziane", "Zighoud Youcef", "Didouche Mourad", "Ibn Ziad", "Messaoud Boudjeriou", "Ouled Rahmoune", "Ain Abid", "Ben Badis"],
  "26 - Médéa": ["Médéa", "Ouzera", "Berrrouaghia", "Ksar El Boukhari", "Chahbounia", "Chellalet El Adhaoura", "Aziz", "Seghouane", "Si Mahdjoub", "Ouamri", "Tablat", "Aïn Boucif", "Beni Slimane"],
  "27 - Mostaganem": ["Mostaganem", "Sayada", "Hassi Maameche", "Mazagran", "Stidia", "Bouguirat", "Sirat", "Ain Sidi Cherif", "Mesra", "Mansourah", "Sidi Lakhdar", "Achaacha"],
  "28 - M'Sila": ["M'Sila", "Bou Saâda", "Sidi Aïssa", "Magra", "Berhoum", "Hammam Dhalaa", "Ouled Derradj", "Belaiba", "Khoubana", "Tamsa", "Ben S'Rour", "Ouled Sidi Brahim"],
  "29 - Mascara": ["Mascara", "Sig", "Mohammadia", "Ghriss", "Tighennif", "Oued Taria", "Aïn Fekan", "Bou Henni", "Zahana", "Oggaz", "Aïn Fares", "Hachem"],
  "30 - Ouargla": ["Ouargla", "N'Goussa", "Hassi Messaoud", "Rouissat", "Sidi Khouiled", "Ain Beida", "El Borma"],
  "31 - Oran": ["Oran", "Es Sénia", "Bir El Djir", "Arzew", "Gdyel", "Hassi Bounif", "Hassi Ben Okba", "Sidi Chami", "Aïn El Turk", "Bousfer", "El Ançor", "Mers El Kébir"],
  "32 - El Bayadh": ["El Bayadh", "Rogassa", "Stitten", "Brezina", "Ghassoul", "Labiodh Sidi Cheikh", "Boualem", "Boussemghoun", "Chellala", "El Abiodh Sidi Cheikh", "Arbaouat"],
  "33 - Illizi": ["Illizi", "In Amenas", "Bordj Omar Driss", "Debdeb"],
  "34 - Bordj Bou Arréridج": ["Bordj Bou Arréridj", "Ras El Oued", "Bordj Ghedir", "Mansoura", "Bordj Zemoura", "El M'hir", "Bir Kasdali", "Medjana", "Teniet En Nasr"],
  "35 - Boumerdès": ["Boumerdès", "Boudouaou", "Dellys", "Khemis El Khechna", "Isser", "Thenia", "Afir", "Bordj Menaïel", "Baghlia", "Sidi Daoud", "Naciria", "Ouled Moussa"],
  "36 - El Tarf": ["El Tarf", "El Kala", "Dréan", "Besbes", "Ben Mehidi", "Bouhadjar", "Zerit", "Chefia", "Lakehal", "Souarekh", "Ramla"],
  "37 - Tindouf": ["Tindouf", "Oum el Assel"],
  "38 - Tissemsilt": ["Tissemsilt", "Lardjem", "Theniet El Had", "Bordj Bou Naama", "Lazharia", "Khemisti", "Ammari", "Youssoufia", "Maacem"],
  "39 - El Oued": ["El Oued", "Bayadha", "Robbah", "Guémar", "Magrane", "Hassi Khalifa", "Debila", "Reguiba", "Kouinine", "Mih Ouensa"],
  "40 - Khenchela": ["Khenchela", "Kaïs", "Chechar", "Babar", "Hamma", "Ouled Rechache", "Bouhmama", "El Mahmal", "Ensigha", "Remila"],
  "41 - Souk Ahras": ["Souk Ahras", "M'daourouch", "Sedrata", "Haddada", "Khedara", "Taoura", "Merahna", "Ouled Driss", "Ouled Moumen", "Bir Bouhouche"],
  "42 - Tipaza": ["Tipaza", "Cherchell", "Koléa", "Bou Ismaïl", "Hadjout", "Gouraya", "Damous", "Ahmer El Aïn", "Sidi Amar", "Nador", "Fouka", "Bouharoun"],
  "43 - Mila": ["Mila", "Chelghoum Laïd", "Ferdjioua", "Grarem Gouga", "Oued Athmania", "Rouached", "Tessala Lemtaï", "Tadjenanet", "Teleghma", "Sidi Khelifa"],
  "44 - Aïn Defla": ["Aïn Defla", "Khemis Miliana", "Miliana", "Hammam Righa", "Boumedfaâ", "Djelida", "Djendel", "El Attaf", "Rouina", "El Abadia", "Bordj Emir Khaled"],
  "45 - Naâma": ["Naâma", "Mécheria", "Aïn Séfra", "Tiout", "Sfissifa", "Moghrar", "Asla", "Kasdir", "Makmen Ben Amar"],
  "46 - Aïn Témoucheنت": ["Aïn Témouchent", "Béni Saf", "Hammam Bou Hadjar", "El Amria", "El Malah", "Sidi Ben Adda", "Oulhaça Gheraba", "Sidi Safi"],
  "47 - Ghardaïa": ["Ghardaïa", "Metlili", "El Guerrara", "Bounoura", "Dhayet Bendhahoua", "Zelfana", "Sebseb", "Berriane"],
  "48 - Relizane": ["Relizane", "Oued Rhiou", "Mazouna", "Zemmora", "Yellel", "Mendes", "Ammi Moussa", "Hamri", "Sidi M'Hamed Ben Ali", "El Hassi"],
  "49 - El M'Ghair": ["El M'Ghair", "Djamaa", "M'Rara", "Still"],
  "50 - El Meniaa": ["El Meniaa", "Hassi Gara", "Hassi El Gara"],
  "51 - Ouled Djellal": ["Ouled Djellal", "Sidi Khaled", "Besbes", "Chaïba", "Doucen", "Ras El Miaad"],
  "52 - Bordj Badji Mokhtar": ["Bordj Badji Mokhtar", "Timiaouine"],
  "53 - Béni Abbès": ["Béni Abbès", "Igli", "Tabelbala", "El Ouata", "Kerzaz", "Tamtert", "Ksabi", "Ougarta"],
  "54 - Timimoun": ["Timimoun", "Ksar Kaddour", "Ouled Said", "Aougrout", "Deldoul", "Metarfa", "Talmine", "Tinerkouk"],
  "55 - Touggourt": ["Touggourt", "N'Goussa", "Tamacine", "Sidi Slimane", "Blidet Amor", "El Hadjira", "El Alia", "Taibet", "M'Naguer", "Benaceur"],
  "56 - Djanet": ["Djanet", "Bordj El Haouas"],
  "57 - In Salah": ["In Salah", "In Ghar", "Foggaret Ezzaouia"],
  "58 - In Guezzam": ["In Guezzam", "Tin Zaouatine"]
};
